language: python

sudo: false

python:
  # - 2.7
  - 3.3
  # - 3.4
  # - 3.5

env:
  matrix:
    - PEP=false

matrix:
  include:
    - python: 2.7
      env: PEP=true

addons:
  apt:
    sources:
      - r-packages-precise
    packages:
      - r-base-dev

cache:
  directories:
    - ~/Rlib

before_install:
  - R --version
  - Rscript --version

  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > ~/.Renviron
  - echo 'options(repos = "http://cran.rstudio.com")' > ~/.Rprofile

  - cat ~/.Renviron
  - cat ~/.Rprofile

  - Rscript -e "install.packages('knitr', dependencies=TRUE)"
  - ls ~/Rlib

install:
  - pip install pep8
  - pip install .

before_script:
  - export LANG=EN_US.UTF-8

script:
  - cat ~/.Renviron
  - ls ~/Rlib
  - Rscript -e 'require(knitr)'
  - if $PEP; then pep8 notedown; fi
  - if ! $PEP; then nosetests; fi
