language: python

sudo: false

python:
  - 2.7
  - 3.3
  - 3.4
  - 3.5

env:
  matrix:
    - PEP=false

matrix:
  include:
    - python: 2.7
      env: PEP=true

addons:
  apt:
    packages:
    - r-base

before_install:
  - mkdir -p ~/Rlib
  - echo 'R_LIBS=~/Rlib' > ~/.Renviron
  - Rscript -e "install.packages('knitr', dependencies=TRUE, repos='http://cran.rstudio.com')"

install:
  - pip install pep8
  - pip install .

before_script:
    - export LANG=EN_US.UTF-8
script:
    - if $PEP; then pep8 notedown; fi
    - if ! $PEP; then nosetests; fi
